# Generated by Django 2.0.5 on 2018-05-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
	    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	    ('App', '0001_initial'),
    ]

    operations = [
	    migrations.AddField(
            model_name='friendship',
            name='Friend',
		    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to=settings.AUTH_USER_MODEL),
        ),
	    migrations.AddField(
            model_name='friendship',
            name='User',
		    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
