# Generated by Django 2.1a1 on 2018-06-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='profile',
			name='PhotoUUID',
		),
		migrations.AddField(
			model_name='profile',
			name='ProfilePhoto',
			field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.Photo'),
		),
	]
