# Generated by Django 2.1a1 on 2018-06-04 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0002_auto_20180604_0015'),
	]

	operations = [
		migrations.AlterField(
			model_name='photo',
			name='Gallery',
			field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Gallery'),
		),
	]
