# Generated by Django 2.0.3 on 2018-04-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_photo_photocomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='App.User')),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='App.User')),
            ],
        ),
    ]
