# Generated by Django 2.0.3 on 2018-04-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='Friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to='App.User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='App.User'),
        ),
    ]
