# Generated by Django 2.0.5 on 2018-05-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0006_auto_20180404_2005'),
	]

	operations = [
		migrations.AddField(
			model_name='photo',
			name='Location',
			field=models.CharField(blank=True, default=None, max_length=100, null=True),
		),
	]
