# Generated by Django 2.0.5 on 2018-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0007_photo_location'),
	]

	operations = [
		migrations.AlterField(
			model_name='photo',
			name='Location',
			field=models.CharField(blank=True, default='', max_length=100, null=True),
		),
	]
