# Generated by Django 2.0.5 on 2018-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0008_auto_20180522_0030'),
	]

	operations = [
		migrations.AddField(
			model_name='photo',
			name='Description',
			field=models.CharField(blank=True, default='', max_length=1024, null=True),
		),
	]
