# Generated by Django 2.0.5 on 2018-05-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0009_photo_description'),
	]

	operations = [
		migrations.CreateModel(
			name='Like',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Photo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Photo')),
				('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.User')),
			],
		),
	]
