# Generated by Django 2.0.5 on 2018-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('App', '0010_like'),
	]

	operations = [
		migrations.AlterField(
			model_name='photocomment',
			name='UploadDateTime',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
